### ISSUE TITLE
Xperia 1 III (XQ-BC72) error, no sync response

### ISSUE THREAD

**Issue by hr3lxphr6j** [munjeni/newflasher#42]
The device does not automatically restart after the flashing is completed. After manually disconnecting the USB link, the device restarts indefinitely.

Full log: https://gist.github.com/hr3lxphr6j/e8648ee88c32fba0364fe38c5d3ed2c8

**Comment by munjeni** [comment]
Hi, reboot mode at the end of flashing:  typa 'a' for reboot to android, type 'f' for reboot to fastboot, type 's' for reboot to same mode, type 'p' for poweroff, and press ENTER. In your case you typed "p" which mean powerdown, you can't expect reboot! Relation to sync isue yes its well known for years, non fix-able since newflasher don't know what device doing in background, sugestion is reflash fw again

**Comment by munjeni** [comment]
https://github.com/munjeni/newflasher/blob/master/newflasher.c#L5110

In next version I will change to 2 minute sync wait time hope it get enought for sync

**Comment by hr3lxphr6j** [comment]
I modified the waiting time of sync based on the v49, and now I can complete the flashing, THX.

**Comment by munjeni** [comment]
Can you please try version 50 from here https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/post-85438351 and give me log?

**Comment by earthlock** [comment]
> I modified the waiting time of sync based on the v49, and now I can complete the flashing, THX.

how does this work? without active a?

**Comment by munjeni** [comment]
You must give a better question
