### ISSUE TITLE
Support to switch between slots

### ISSUE THREAD

**Issue by linuxct** [munjeni/newflasher#49]
Hi,

[@rmrfl5](https://t.me/rmrfl5) has softbricked his Xperia 5 II due to flashing his device with newflasher while the currently active slot is 'b'. Due to super.sin containing a valid image set for the slot a, but an empty or otherwise non-bootable image set on slot b, the phone is now not able to boot. The phone's bootloader is locked, and trying to switch slots with fastboot results in an error.

For this reason, I made a small snippet in newflasher's source that switches the currently active slot to the **opposite** slot than the one that's selected. [patch-0001.zip](https://github.com/munjeni/newflasher/files/8218852/patch-0001.zip)

Obviously, I am *not* going to submit that to upstream. But I cannot test it either due to unclear instructions on how to replicate the build environment needed to make the windows crossbuild.

Would you please help me build newflasher for windows with the patch I submitted so that we can make [@rmrfl5](https://t.me/rmrfl5)'s device boot again?
Thank you.

**Comment by linuxct** [comment]
We fixed the issue by running `newflasher set_active:a`. It would be nice if the fact that sending individual commands is a possibility within newflasher. One would not expect to be able to write extra parameters for a program that has no built-in help, and doesn't say it accepts them when you run it. And I have not seen this documented neither here or in the XDA thread. Closing the issue.

**Comment by munjeni** [comment]
Hi, I'm allready mentioned in changelog about new features inside newflasher:

- version v24 (04.07.2020)
new feature - now you can run newflasher from script or console with your own command, e.g. newflasher getvar:Emmc-info , I didn't tested all the list of commands, if you do it share them with us!

You can do a lot of things, yes its not documented because I didn't tested few, but you can try some, for example:

newflasher getvar:Emmc-info (a lot of similar commands can be done)
newflasher Read-TA:2:2050 (this one will read last boot log from bootloader! A lot of other trim area units can be read)
- the rest: I don't know, hope somebody get idea :)

**Comment by linuxct** [comment]
Nice, thank you!
